spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/spring-boot-microservices-realm

  cloud:
    gateway:
      mvc:
        routes:
        # Product Service Route
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/products

        # Order Service Route
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/orders

        # Discovery Server Route
          - id: discovery-server
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/

        # Discovery Server Static Resources Route
          - id: discovery-server-static
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:

  # Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  tracing:
    sampling:
      probability: 1.0
